# Generated by Django 3.2.23 on 2024-02-07 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_auto_20240207_0521'),
        ('core', '0007_auto_20240125_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='current_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classrooms.class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classrooms.class'),
        ),
    ]
