# Generated by Django 3.2.23 on 2024-02-07 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedules',
            fields=[
                ('schedule_id', models.IntegerField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(max_length=20)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='friday_schedule',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='monday_schedule',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='thursday_schedule',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='tuesday_schedule',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='wednesday_schedule',
        ),
        migrations.RemoveField(
            model_name='class',
            name='timetable',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.AddField(
            model_name='teachers',
            name='subject_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classrooms.subject'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Schedules',
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
        migrations.AddField(
            model_name='classschedules',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.class'),
        ),
        migrations.AddField(
            model_name='classschedules',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.subject'),
        ),
    ]
