# Generated by Django 3.2.23 on 2024-02-02 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_auto_20240201_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_teacher_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='classrooms.teachers'),
            preserve_default=False,
        ),
    ]
