# Generated by Django 3.2.23 on 2024-02-02 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_class_class_teacher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedules',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='classschedules',
            name='time_start',
        ),
        migrations.AddField(
            model_name='classschedules',
            name='slot',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
            preserve_default=False,
        ),
    ]
