# Generated by Django 3.2.23 on 2024-02-02 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0004_auto_20240202_0735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='class_teacher_id',
            new_name='class_teacher',
        ),
        migrations.RenameField(
            model_name='classschedules',
            old_name='class_id',
            new_name='classroom',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='staff_id',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='subject_id',
            new_name='subject',
        ),
    ]
