# Generated by Django 3.2.23 on 2024-02-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0006_auto_20240205_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='standard',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII')], max_length=255),
        ),
    ]
